public class  Rpg_art
{
	public static void main(String args[])
	{

		System.out.println(" _____  _             _   _  _      _      _                _____                        _  _  _    _               ");
		System.out.println("|_   _|| |           | | | |(_)    | |    | |              |  ___|                      | |(_)| |  (_)              ");
		System.out.println("  | |  | |__    ___  | |_| | _   __| |  __| |  ___  _ __   | |__ __  __ _ __    ___   __| | _ | |_  _   ___   _ __  ");
		System.out.println("  | |  | '_ \\  / _ \\ |  _  || | / _` | / _` | / _ \\| '_ \\  |  __|\\ \\/ /| '_ \\  / _ \\ / _` || || __|| | / _ \\ | '_ \\ ");
		System.out.println("  | |  | | | ||  __/ | | | || || (_| || (_| ||  __/| | | | | |___ >  < | |_) ||  __/| (_| || || |_ | || (_) || | | |");
		System.out.println("  \\_/  |_| |_| \\___| \\_| |_/|_| \\__,_| \\__,_| \\___||_| |_| \\____//_/\\_\\| .__/  \\___| \\__,_||_| \\__||_| \\___/ |_| |_|");
		System.out.println("                                                                       | |                                          ");
		System.out.println("                                                                       |_|                                          ");
		System.out.println("                                                                                                               ");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                                       (                                ");
		System.out.println("                        (                 )  (         )\\ )      (     (    (           ");
		System.out.println("    (                   )\\  )       )  ( /(  )\\   (   (()/( (    )\\ )  )\\ ) )\\   (      ");
		System.out.println("    )\\   (     (    (  ((_)/((   ( /(  )\\())((_) ))\\   /(_)))\\  (()/( (()/(((_) ))\\ (   ");
		System.out.println(" _ ((_)  )\\ )  )\\   )\\  _ (_))\\  )(_))((_)\\  _  /((_) (_)) ((_)  ((_)) ((_))_  /((_))\\  ");
		System.out.println("| | | | _(_/( ((_) ((_)| |_)((_)((_)_ | |(_)| |(_))   | _ \\ (_)  _| |  _| || |(_)) ((_) ");
		System.out.println("| |_| || ' \\))(_-</ _ \\| |\\ V / / _` || '_ \\| |/ -_)  |   / | |/ _` |/ _` || |/ -_)(_-< ");
		System.out.println(" \\___/ |_||_| /__/\\___/|_| \\_/  \\__,_||_.__/|_|\\___|  |_|_\\ |_|\\__,_|\\__,_||_|\\___|/__/ ");
		System.out.println("         ");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println(" ********************************************************************************");
		System.out.println("*                    /   \\              /'\\       _                              *");
		System.out.println("*\\_..           /'.,/     \\_         .,'   \\     / \\_                            *");
		System.out.println("*    \\         /            \\      _/       \\_  /    \\     _                     *");
		System.out.println("*     \\__,.   /              \\    /           \\/.,   _|  _/ \\                    *");
		System.out.println("*          \\_/                \\  /',.,''\\      \\_ \\_/  \\/    \\                   *");
		System.out.println("*                           _  \\/   /    ',../',.\\    _/      \\                  *");
		System.out.println("*             /           _/m\\  \\  /    |         \\  /.,/'\\   _\\                 *");
		System.out.println("*           _/           /MMmm\\  \\_     |          \\/      \\_/  \\                *");
		System.out.println("*          /      \\     |MMMMmm|   \\__   \\          \\_       \\   \\_              *");
		System.out.println("*                  \\   /MMMMMMm|      \\   \\           \\       \\    \\             *");
		System.out.println("*                   \\  |MMMMMMmm\\      \\___            \\_      \\_   \\            *");
		System.out.println("*                    \\|MMMMMMMMmm|____.'  /\\_            \\       \\   \\_          *");
		System.out.println("*                    /'.,___________...,,'   \\            \\   \\        \\         *");
		System.out.println("*                   /       \\          |      \\    |__     \\   \\_       \\        *");
		System.out.println("*                 _/        |           \\      \\_     \\     \\    \\       \\_      *");
		System.out.println("*                /                               \\     \\     \\_   \\        \\     *");
		System.out.println("*                                                 \\     \\      \\   \\__      \\    *");
		System.out.println("*                                                  \\     \\_     \\     \\      \\   *");
		System.out.println("*                                                   |      \\     \\     \\      \\  *");
		System.out.println("*                                                    \\ms          |            \\ *");
		System.out.println(" ********************************************************************************");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("");
		System.out.println("                                                                               ");
	
		 System.out.println("___________      .__      .__         ___________.__                ");
         System.out.println("\\__    ___/______|__|__  _|__|____    \\__    ___/|__| _____   ____  ");
         System.out.println("  |    |  \\_  __ \\  \\  \\/ /  \\__  \\     |    |   |  |/     \\_/ __ \\ ");
         System.out.println("  |    |   |  | \\/  |\\   /|  |/ __ \\_   |    |   |  |  Y Y  \\  ___/ ");
         System.out.println("  |____|   |__|  |__| \\_/ |__(____  /   |____|   |__|__|_|  /\\___  >");
         System.out.println("                                  \\/                      \\/     \\/ ");
         System.out.println("");
         System.out.println("");
         System.out.println("");
         System.out.println("");
         System.out.println("");
         System.out.println("");
         System.out.println("");
         System.out.println("");
         System.out.println("");
         System.out.println("                                                            ---\\=,</");
         System.out.println("..,.,.,,.,.,.,,.,._,,,____,,,...,.,.,,.....,....,.,..,,.  ,-=--'\\\\_\\/");
         System.out.println("\"\"\"\"\"\"\"\"\"\"############z_ _`\"\"\"########################' ,---'>__,>,_`-.     |");
         System.out.println("       :  |  `\"\"\"V#######,,_ `-  \"\"##################' --z--;\" /_/  `. `.   |");
         System.out.println("          |          `/\"\"\"\".`|`|| } }|.\"\"\"\"\"\"\"\"|\"\"\"\"\"  --'//`/'  `    \\  '. |");
         System.out.println("    :          :      |:     ||   |  |  :   :  |   :   ,_\\---_\\._   :  `.\\ |/");
         System.out.println("                   :  /  :   |  |   || :  :      :    //--'> ___ ``-,_   \\  \\");
         System.out.println("         `\"^            :  ` ||   || |   :  :         '=-`',' / `-, __`-. |");
         System.out.println("      :    :          : :  : |  |    ||    :     ---  //7;<\\     / ,--._ ` |");
         System.out.println("         .,      :        :  |   ||| || '       :     -/;\\'/` -='/|(    \\ \\");
         System.out.println("        %#'            :    `| |||    |  :   :      :  // '\\   // | `    | |");
         System.out.println("    :         :   `'   :  :  || # | |||    :            `    .        :  | ");
         System.out.println("                         :   | ||#|#| | ':    :    :             :       ` ");
         System.out.println("         '#\"      :   :    : | ||,|, ||   :      /        :           |:  ||");
         System.out.println("  \"\"'                    :  \\\\|\\ X XX///`      :|   :    |   :      : |   |");
         System.out.println("        :             :  / >\\\\> <\\/\\< </</==::_ |' ,`  ,.|_____|______|`--|");
         System.out.println("   :         :   |    ,''{` /\"^\"/'/\\^\\'\"\\ --  \"\"\"==;:zz,,_;__ ,; : , ,,hjm|");
         System.out.println("        |'       |`--', ',`--,,_    -_ --.  `--.     __ \"\"`\"=;;--=--=;;-==||");
         System.out.println("        |    ,,--' ''  ,` ,',' ,'`--,._    -=-  /%%\\.___     ---          |");
         System.out.println("  :     |---'  '  ' ,' ,`` , .'`.,,` , ';'--,._   `-=='  ~~  __ __ _,  ~~ |");
         System.out.println("     :,-',' '` `` ,  .`, ,',' ', ` , ,','',`, `'\"`--,,_____..__          / |");
         System.out.println(",,---',  ' ' , , '  ', , ` ' ,' `, ,  , ` '` ',`,`,` ,',' ',, ,`\"\"'--~',' /");
         System.out.println("");
         System.out.println("");
         System.out.println("");
         System.out.println(" ____  ____  ____  _     _____  ___  _ ____  _     ____    _      ____  _____  _       ____  _  __ _  _     _     ____ ");
         System.out.println("/  __\\/  __\\/  _ \\/ \\ |\\/  __/  \\  \\///  _ \\/ \\ /\\/  __\\  / \\__/|/  _ \\/__ __\\/ \\ /|  / ___\\/ |/ // \\/ \\   / \\   / ___\\");
         System.out.println("|  \\/||  \\/|| / \\|| | //|  \\     \\  / | / \\|| | |||  \\/|  | |\\/||| / \\|  / \\  | |_||  |    \\|   / | || |   | |   |    \\");
         System.out.println("|  __/|    /| \\_/|| \\// |  /_    / /  | \\_/|| \\_/||    /  | |  ||| |-||  | |  | | ||  \\___ ||   \\ | || |_/\\| |_/\\\\___ |");
         System.out.println("\\_/   \\_/\\_\\\\____/\\__/  \\____\\  /_/   \\____/\\____/\\_/\\_\\  \\_/  \\|\\_/ \\|  \\_/  \\_/ \\|  \\____/\\_|\\_\\\\_/\\____/\\____/\\____/");
         System.out.println("                                                                                                                       ");
         System.out.println("");
         System.out.println(" _  _    ___    __  __  _  _      _      ____   ");
         System.out.println("( \\/ )  (___)  (  \\/  )( \\/ )   _| |_   (  _ \\  ");
         System.out.println(" \\  /    ___    )    (  )  (   (_   _)   ) _ <  ");
         System.out.println(" (__)   (___)  (_/\\/\\_)(_/\\_)    |_|    (____/  ");
         System.out.println(" _  _    ___    __           ____         _   _ ");
         System.out.println("( \\/ )  (___)  (  )    \\|/  (  _ \\  \\|/  ( )_( )");
         System.out.println(" \\  /    ___    )(__   /|\\   ) _ <  /|\\   ) _ ( ");
         System.out.println("  \\/    (___)  (____)       (____/       (_) (_)");
         System.out.println("                                                ");
	
	}
}
